// Mock Data for QueueSense AI — Intelligent Hospital Waiting-Time & Patient Flow System

export const INITIAL_DEPARTMENTS = [
  {
    id: 'gen-med',
    code: 'GM',
    name: 'General Medicine',
    malayalamName: 'ജനറൽ മെഡിസിൻ',
    location: 'Ground Floor, Block A',
    avgServiceTimeMinutes: 7.5,
    activeCounters: 3,
    totalCounters: 4,
    color: '#0d9488',
    counters: [
      { id: 'gm-c1', number: 1, doctor: 'Dr. Radhakrishnan K.', status: 'busy', currentToken: 'GM-104' },
      { id: 'gm-c2', number: 2, doctor: 'Dr. Sunitha Menon', status: 'busy', currentToken: 'GM-103' },
      { id: 'gm-c3', number: 3, doctor: 'Dr. Arun Varma', status: 'available', currentToken: null },
      { id: 'gm-c4', number: 4, doctor: 'Staff Nurse / Triage', status: 'offline', currentToken: null },
    ]
  },
  {
    id: 'pediatrics',
    code: 'PED',
    name: 'Pediatrics',
    malayalamName: 'ശിശുരോഗ വിഭാഗം',
    location: 'First Floor, Block B',
    avgServiceTimeMinutes: 9.0,
    activeCounters: 2,
    totalCounters: 3,
    color: '#0284c7',
    counters: [
      { id: 'ped-c1', number: 1, doctor: 'Dr. Priya Nair', status: 'busy', currentToken: 'PED-042' },
      { id: 'ped-c2', number: 2, doctor: 'Dr. Thomas George', status: 'available', currentToken: null },
      { id: 'ped-c3', number: 3, doctor: 'Counter 3', status: 'offline', currentToken: null },
    ]
  },
  {
    id: 'orthopedics',
    code: 'ORTHO',
    name: 'Orthopedics',
    malayalamName: 'അസ്ഥിരോഗ വിഭാഗം',
    location: 'Ground Floor, Block C',
    avgServiceTimeMinutes: 11.5,
    activeCounters: 2,
    totalCounters: 2,
    color: '#6366f1',
    counters: [
      { id: 'ortho-c1', number: 1, doctor: 'Dr. Mathew Joseph', status: 'busy', currentToken: 'ORTHO-088' },
      { id: 'ortho-c2', number: 2, doctor: 'Dr. Deepa S.', status: 'busy', currentToken: 'ORTHO-087' },
    ]
  },
  {
    id: 'ent',
    code: 'ENT',
    name: 'ENT (Ear, Nose, Throat)',
    malayalamName: 'ഇ എൻ ടി വിഭാഗം',
    location: 'Second Floor, Block A',
    avgServiceTimeMinutes: 6.5,
    activeCounters: 1,
    totalCounters: 2,
    color: '#f59e0b',
    counters: [
      { id: 'ent-c1', number: 1, doctor: 'Dr. Suresh Kumar', status: 'busy', currentToken: 'ENT-029' },
      { id: 'ent-c2', number: 2, doctor: 'Counter 2', status: 'offline', currentToken: null },
    ]
  },
  {
    id: 'ophthalmology',
    code: 'EYE',
    name: 'Ophthalmology',
    malayalamName: 'നേത്രരോഗ വിഭാഗം',
    location: 'Second Floor, Block B',
    avgServiceTimeMinutes: 8.0,
    activeCounters: 1,
    totalCounters: 2,
    color: '#10b981',
    counters: [
      { id: 'eye-c1', number: 1, doctor: 'Dr. Anjali Pillai', status: 'available', currentToken: null },
      { id: 'eye-c2', number: 2, doctor: 'Counter 2', status: 'offline', currentToken: null },
    ]
  },
  {
    id: 'gynecology',
    code: 'GYN',
    name: 'Gynecology & Obstetrics',
    malayalamName: 'സ്ത്രീരോഗ വിഭാഗം',
    location: 'First Floor, Block A',
    avgServiceTimeMinutes: 10.0,
    activeCounters: 2,
    totalCounters: 2,
    color: '#ec4899',
    counters: [
      { id: 'gyn-c1', number: 1, doctor: 'Dr. Lakshmi Ramesh', status: 'busy', currentToken: 'GYN-051' },
      { id: 'gyn-c2', number: 2, doctor: 'Dr. Rema Devi', status: 'available', currentToken: null },
    ]
  }
];

export const INITIAL_TOKENS = [
  // General Medicine Tokens
  {
    id: 'tok-101',
    tokenNumber: 'GM-101',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8219 (K. Raman, 68y)',
    anonymizedName: 'Patient K.R.',
    ageGroup: 'Senior Citizen (60+)',
    visitType: 'Walk-in OPD',
    registrationTime: '08:45 AM',
    registrationTimestamp: Date.now() - 75 * 60 * 1000,
    status: 'Completed',
    counterServed: 'Counter 1 (Dr. Radhakrishnan K.)',
    completedAt: '09:02 AM',
    serviceDurationMinutes: 8,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: ['Wheelchair Assistance'],
  },
  {
    id: 'tok-102',
    tokenNumber: 'GM-102',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8224 (M. Varghese, 45y)',
    anonymizedName: 'Patient M.V.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Scheduled Follow-up',
    registrationTime: '08:52 AM',
    registrationTimestamp: Date.now() - 68 * 60 * 1000,
    status: 'Completed',
    counterServed: 'Counter 2 (Dr. Sunitha Menon)',
    completedAt: '09:09 AM',
    serviceDurationMinutes: 7,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-103',
    tokenNumber: 'GM-103',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8230 (A. Fathima, 54y)',
    anonymizedName: 'Patient A.F.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:05 AM',
    registrationTimestamp: Date.now() - 45 * 60 * 1000,
    status: 'In Service',
    counterServed: 'Counter 2 (Dr. Sunitha Menon)',
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: ['Malayalam Voice Prompt'],
  },
  {
    id: 'tok-104',
    tokenNumber: 'GM-104',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8238 (S. Devassy, 79y)',
    anonymizedName: 'Patient S.D.',
    ageGroup: 'Super Senior (75+)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:12 AM',
    registrationTimestamp: Date.now() - 38 * 60 * 1000,
    status: 'Called',
    counterServed: 'Counter 1 (Dr. Radhakrishnan K.)',
    isPriority: true,
    priorityReason: 'Frail Super-Senior Mobility Assistance',
    priorityStaffNote: 'Verified by Reception Nurse Sister Bindu at 09:12 AM. Wheelchair provided.',
    priorityVerifiedBy: 'Sister Bindu (Staff Nurse - ID #412)',
    accessibilityNeeds: ['Wheelchair Assistance', 'Malayalam Voice Prompt'],
  },
  {
    id: 'tok-105',
    tokenNumber: 'GM-105',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8245 (R. Chandran, 38y)',
    anonymizedName: 'Patient R.C.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:18 AM',
    registrationTimestamp: Date.now() - 32 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-106',
    tokenNumber: 'GM-106',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8251 (J. Mathew, 29y)',
    anonymizedName: 'Patient J.M.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:25 AM',
    registrationTimestamp: Date.now() - 25 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-107',
    tokenNumber: 'GM-107',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8260 (B. Thankam, 71y)',
    anonymizedName: 'Patient B.T.',
    ageGroup: 'Senior Citizen (60+)',
    visitType: 'Referral Case',
    registrationTime: '09:31 AM',
    registrationTimestamp: Date.now() - 19 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: true,
    priorityReason: 'Post-Chemotherapy Weakness Review',
    priorityStaffNote: 'Authorized oncology day-care cross-referral note by Dr. Menon.',
    priorityVerifiedBy: 'Sister Bindu (Staff Nurse - ID #412)',
    accessibilityNeeds: ['Malayalam Voice Prompt'],
  },
  {
    id: 'tok-108',
    tokenNumber: 'GM-108',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8268 (N. Pradeep, 52y)',
    anonymizedName: 'Patient N.P.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:38 AM',
    registrationTimestamp: Date.now() - 12 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-109',
    tokenNumber: 'GM-109',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8274 (G. Mary, 64y)',
    anonymizedName: 'Patient G.M.',
    ageGroup: 'Senior Citizen (60+)',
    visitType: 'Scheduled Follow-up',
    registrationTime: '09:44 AM',
    registrationTimestamp: Date.now() - 6 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-110',
    tokenNumber: 'GM-110',
    departmentId: 'gen-med',
    departmentCode: 'GM',
    patientRef: 'REF-8280 (H. Nazeer, 41y)',
    anonymizedName: 'Patient H.N.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:48 AM',
    registrationTimestamp: Date.now() - 2 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },

  // Pediatrics Tokens
  {
    id: 'tok-201',
    tokenNumber: 'PED-041',
    departmentId: 'pediatrics',
    departmentCode: 'PED',
    patientRef: 'REF-9102 (Child A. Kumar, 4y)',
    anonymizedName: 'Child A.K.',
    ageGroup: 'Pediatric (< 12)',
    visitType: 'Walk-in OPD',
    registrationTime: '08:50 AM',
    registrationTimestamp: Date.now() - 70 * 60 * 1000,
    status: 'Completed',
    counterServed: 'Counter 1 (Dr. Priya Nair)',
    completedAt: '09:05 AM',
    serviceDurationMinutes: 10,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-202',
    tokenNumber: 'PED-042',
    departmentId: 'pediatrics',
    departmentCode: 'PED',
    patientRef: 'REF-9114 (Infant D. George, 8m)',
    anonymizedName: 'Infant D.G.',
    ageGroup: 'Infant (< 1)',
    visitType: 'Vaccination & Check',
    registrationTime: '09:02 AM',
    registrationTimestamp: Date.now() - 48 * 60 * 1000,
    status: 'In Service',
    counterServed: 'Counter 1 (Dr. Priya Nair)',
    isPriority: true,
    priorityReason: 'High Febrile Episode under 1 yr',
    priorityStaffNote: 'Triage nurse verified temperature 102.4 F. Fast-track requested for pediatric review.',
    priorityVerifiedBy: 'Sister Anu (Triage Nurse - ID #208)',
    accessibilityNeeds: ['Malayalam Voice Prompt'],
  },
  {
    id: 'tok-203',
    tokenNumber: 'PED-043',
    departmentId: 'pediatrics',
    departmentCode: 'PED',
    patientRef: 'REF-9128 (Child R. Rahul, 7y)',
    anonymizedName: 'Child R.R.',
    ageGroup: 'Pediatric (< 12)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:20 AM',
    registrationTimestamp: Date.now() - 30 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-204',
    tokenNumber: 'PED-044',
    departmentId: 'pediatrics',
    departmentCode: 'PED',
    patientRef: 'REF-9135 (Child S. Sneha, 10y)',
    anonymizedName: 'Child S.S.',
    ageGroup: 'Pediatric (< 12)',
    visitType: 'Scheduled Follow-up',
    registrationTime: '09:35 AM',
    registrationTimestamp: Date.now() - 15 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },

  // Orthopedics Tokens
  {
    id: 'tok-301',
    tokenNumber: 'ORTHO-087',
    departmentId: 'orthopedics',
    departmentCode: 'ORTHO',
    patientRef: 'REF-7032 (V. Sukumaran, 62y)',
    anonymizedName: 'Patient V.S.',
    ageGroup: 'Senior Citizen (60+)',
    visitType: 'Plaster Removal',
    registrationTime: '09:00 AM',
    registrationTimestamp: Date.now() - 50 * 60 * 1000,
    status: 'In Service',
    counterServed: 'Counter 2 (Dr. Deepa S.)',
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: ['Wheelchair Assistance'],
  },
  {
    id: 'tok-302',
    tokenNumber: 'ORTHO-088',
    departmentId: 'orthopedics',
    departmentCode: 'ORTHO',
    patientRef: 'REF-7041 (M. Abraham, 56y)',
    anonymizedName: 'Patient M.A.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:10 AM',
    registrationTimestamp: Date.now() - 40 * 60 * 1000,
    status: 'Called',
    counterServed: 'Counter 1 (Dr. Mathew Joseph)',
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-303',
    tokenNumber: 'ORTHO-089',
    departmentId: 'orthopedics',
    departmentCode: 'ORTHO',
    patientRef: 'REF-7053 (T. Kuriakose, 73y)',
    anonymizedName: 'Patient T.K.',
    ageGroup: 'Senior Citizen (60+)',
    visitType: 'Acute Joint Pain',
    registrationTime: '09:28 AM',
    registrationTimestamp: Date.now() - 22 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: true,
    priorityReason: 'Severe Immobility / Acute Knee Sprain',
    priorityStaffNote: 'Orthopedic orderly assigned stretcher-to-wheelchair support.',
    priorityVerifiedBy: 'Sister Anu (Triage Nurse - ID #208)',
    accessibilityNeeds: ['Wheelchair Assistance', 'Malayalam Voice Prompt'],
  },

  // ENT Tokens
  {
    id: 'tok-401',
    tokenNumber: 'ENT-029',
    departmentId: 'ent',
    departmentCode: 'ENT',
    patientRef: 'REF-6012 (P. Anirudhan, 33y)',
    anonymizedName: 'Patient P.A.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:15 AM',
    registrationTimestamp: Date.now() - 35 * 60 * 1000,
    status: 'In Service',
    counterServed: 'Counter 1 (Dr. Suresh Kumar)',
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-402',
    tokenNumber: 'ENT-030',
    departmentId: 'ent',
    departmentCode: 'ENT',
    patientRef: 'REF-6025 (K. Shylaja, 49y)',
    anonymizedName: 'Patient K.S.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Walk-in OPD',
    registrationTime: '09:33 AM',
    registrationTimestamp: Date.now() - 17 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: ['Hearing/Speech Assistance'],
  },

  // Gynecology Tokens
  {
    id: 'tok-501',
    tokenNumber: 'GYN-051',
    departmentId: 'gynecology',
    departmentCode: 'GYN',
    patientRef: 'REF-5022 (S. Anitha, 28y)',
    anonymizedName: 'Patient S.A.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Antenatal Check',
    registrationTime: '09:05 AM',
    registrationTimestamp: Date.now() - 45 * 60 * 1000,
    status: 'In Service',
    counterServed: 'Counter 1 (Dr. Lakshmi Ramesh)',
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  },
  {
    id: 'tok-502',
    tokenNumber: 'GYN-052',
    departmentId: 'gynecology',
    departmentCode: 'GYN',
    patientRef: 'REF-5034 (R. Bhavani, 31y)',
    anonymizedName: 'Patient R.B.',
    ageGroup: 'Adult (18-59)',
    visitType: 'Follow-up',
    registrationTime: '09:22 AM',
    registrationTimestamp: Date.now() - 28 * 60 * 1000,
    status: 'Waiting',
    counterServed: null,
    isPriority: false,
    priorityReason: null,
    accessibilityNeeds: [],
  }
];

export const INITIAL_PRIORITY_FLAGS = [
  {
    id: 'flag-1',
    tokenId: 'tok-104',
    tokenNumber: 'GM-104',
    departmentId: 'gen-med',
    departmentName: 'General Medicine',
    patientRef: 'REF-8238 (S. Devassy, 79y)',
    ageGroup: 'Super Senior (75+)',
    reason: 'Frail Super-Senior Mobility Assistance',
    staffNote: 'Verified by Reception Nurse Sister Bindu at 09:12 AM. Patient is unable to stand for prolonged period. Wheelchair provided.',
    reviewer: 'Sister Bindu (Staff Nurse - ID #412)',
    timestamp: '09:12 AM',
    status: 'Confirmed', // Pending, Confirmed, Overridden, Resolved
    auditLog: [
      { action: 'Flag Created', user: 'Sister Bindu (Staff Nurse)', time: '09:12 AM', note: 'Marked as priority during registration counter check.' },
      { action: 'Priority Confirmed', user: 'Dr. Radhakrishnan K. (Chief MO)', time: '09:15 AM', note: 'Priority expedited to Counter 1.' }
    ]
  },
  {
    id: 'flag-2',
    tokenId: 'tok-107',
    tokenNumber: 'GM-107',
    departmentId: 'gen-med',
    departmentName: 'General Medicine',
    patientRef: 'REF-8260 (B. Thankam, 71y)',
    ageGroup: 'Senior Citizen (60+)',
    reason: 'Post-Chemotherapy Weakness Review',
    staffNote: 'Cross-referral note presented from RCC Thiruvananthapuram. Immediate doctor consultation recommended.',
    reviewer: 'Sister Bindu (Staff Nurse - ID #412)',
    timestamp: '09:31 AM',
    status: 'Confirmed',
    auditLog: [
      { action: 'Flag Created', user: 'Sister Bindu (Staff Nurse)', time: '09:31 AM', note: 'Cross-referral case verified with medical booklet.' }
    ]
  },
  {
    id: 'flag-3',
    tokenId: 'tok-202',
    tokenNumber: 'PED-042',
    departmentId: 'pediatrics',
    departmentName: 'Pediatrics',
    patientRef: 'REF-9114 (Infant D. George, 8m)',
    ageGroup: 'Infant (< 1)',
    reason: 'High Febrile Episode under 1 yr',
    staffNote: 'Triage nurse verified temperature 102.4 F. Fast-track requested for pediatric review.',
    reviewer: 'Sister Anu (Triage Nurse - ID #208)',
    timestamp: '09:02 AM',
    status: 'Confirmed',
    auditLog: [
      { action: 'Flag Created', user: 'Sister Anu (Triage Nurse)', time: '09:02 AM', note: 'Temperature recorded 102.4 F at initial vital station.' },
      { action: 'Assigned to Dr. Priya Nair', user: 'Dr. Priya Nair', time: '09:03 AM', note: 'Token taken in service immediately.' }
    ]
  },
  {
    id: 'flag-4',
    tokenId: 'tok-303',
    tokenNumber: 'ORTHO-089',
    departmentId: 'orthopedics',
    departmentName: 'Orthopedics',
    patientRef: 'REF-7053 (T. Kuriakose, 73y)',
    ageGroup: 'Senior Citizen (60+)',
    reason: 'Severe Immobility / Acute Knee Sprain',
    staffNote: 'Patient arrived via ambulance stretch assistance. Awaiting doctor examination.',
    reviewer: 'Sister Anu (Triage Nurse - ID #208)',
    timestamp: '09:28 AM',
    status: 'Pending',
    auditLog: [
      { action: 'Flag Created', user: 'Sister Anu (Triage Nurse)', time: '09:28 AM', note: 'Awaiting MO counter confirmation.' }
    ]
  }
];

export const HOURLY_ANALYTICS_DATA = [
  { hour: '08:00 AM', patientsArrived: 28, patientsServed: 18, avgWaitMinutes: 14, skippedTokens: 1, congestionIndex: 32 },
  { hour: '09:00 AM', patientsArrived: 54, patientsServed: 42, avgWaitMinutes: 24, skippedTokens: 3, congestionIndex: 78 },
  { hour: '10:00 AM', patientsArrived: 68, patientsServed: 51, avgWaitMinutes: 32, skippedTokens: 4, congestionIndex: 91 },
  { hour: '11:00 AM', patientsArrived: 62, patientsServed: 58, avgWaitMinutes: 28, skippedTokens: 2, congestionIndex: 82 },
  { hour: '12:00 PM', patientsArrived: 45, patientsServed: 49, avgWaitMinutes: 19, skippedTokens: 1, congestionIndex: 56 },
  { hour: '01:00 PM', patientsArrived: 22, patientsServed: 30, avgWaitMinutes: 12, skippedTokens: 0, congestionIndex: 25 },
  { hour: '02:00 PM', patientsArrived: 35, patientsServed: 33, avgWaitMinutes: 16, skippedTokens: 2, congestionIndex: 44 },
  { hour: '03:00 PM', patientsArrived: 29, patientsServed: 31, avgWaitMinutes: 15, skippedTokens: 1, congestionIndex: 38 },
];

export const WEEKLY_TREND_DATA = [
  { day: 'Mon', totalPatients: 382, avgWaitMinutes: 29.5, onTimeRate: 88, maxWaitMinutes: 52 },
  { day: 'Tue', totalPatients: 412, avgWaitMinutes: 34.0, onTimeRate: 82, maxWaitMinutes: 61 },
  { day: 'Wed', totalPatients: 356, avgWaitMinutes: 26.2, onTimeRate: 91, maxWaitMinutes: 45 },
  { day: 'Thu', totalPatients: 374, avgWaitMinutes: 28.0, onTimeRate: 89, maxWaitMinutes: 48 },
  { day: 'Fri', totalPatients: 440, avgWaitMinutes: 36.8, onTimeRate: 79, maxWaitMinutes: 68 },
  { day: 'Sat', totalPatients: 290, avgWaitMinutes: 21.4, onTimeRate: 94, maxWaitMinutes: 38 },
  { day: 'Sun (OPD Off)', totalPatients: 45, avgWaitMinutes: 12.0, onTimeRate: 98, maxWaitMinutes: 20 },
];

export const DEPARTMENT_COMPARISON_DATA = [
  { department: 'General Medicine', activeCounters: 3, totalTokens: 142, avgWaitMin: 23.5, completedToday: 88, congestion: 'High' },
  { department: 'Pediatrics', activeCounters: 2, totalTokens: 64, avgWaitMin: 18.0, completedToday: 41, congestion: 'Moderate' },
  { department: 'Orthopedics', activeCounters: 2, totalTokens: 52, avgWaitMin: 27.5, completedToday: 32, congestion: 'Moderate' },
  { department: 'ENT', activeCounters: 1, totalTokens: 38, avgWaitMin: 15.2, completedToday: 29, congestion: 'Low' },
  { department: 'Ophthalmology', activeCounters: 1, totalTokens: 34, avgWaitMin: 16.0, completedToday: 25, congestion: 'Low' },
  { department: 'Gynecology', activeCounters: 2, totalTokens: 49, avgWaitMin: 21.0, completedToday: 35, congestion: 'Moderate' },
];

export const DEMO_USERS = [
  { id: 'usr-1', name: 'Sister Bindu K.', role: 'reception', roleName: 'Reception & Triage Staff', department: 'Central Reception Desk', hospital: 'Govt. General Hospital — OPD Wing' },
  { id: 'usr-2', name: 'Dr. Radhakrishnan K.', role: 'doctor', roleName: 'Doctor / Counter Staff', department: 'General Medicine (Counter 1)', hospital: 'Govt. General Hospital — OPD Wing' },
  { id: 'usr-3', name: 'Dr. Girish Mohan', role: 'admin', roleName: 'Hospital Administrator / RMO', department: 'Medical Administration', hospital: 'Govt. General Hospital — OPD Wing' },
];
